source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'MJRefresh'
#pod 'SDCycleScrollView'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SDWebImage'
pod 'StarWars'
pod 'SSLunarDate'
pod 'UMengAnalytics'
